<?php
$data=[
"geppei-lab"=>[
"level"=>"3",
"passwd"=>"lnlabPw1crosslaw",
"name"=>"Administrator(仮)"
],
"member"=>[
"level"=>"1",
"passwd"=>"member",
"name"=>"Memberテスト"
],
"notify"=>[
"level"=>"2",
"passwd"=>"test",
"name"=>"Notifyテスト"
],
"nyanpass"=>[
"level"=>"3",
"passwd"=>"t1s5r9y8",
"name"=>"にゃんぱす"
]];

file_put_contents("users.json",json_encode($data));
